---
title: "STT2860 Introduction to Data<br>Management & Visualization<br>Assessment Map for Fall 2023"
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
    css: "../../css/style.css"
    keep_md: yes
---

<hr>
**This document is a work in progress.**
<hr>

## Assessment Map

**1. Students will learn to use a reproducible research workflow.**

* Week 07: | DC | Reporting with R Markdown
* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

**2. Students will learn to collaborate effectively to solve problems.**

* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

**3. Students will develop their expertise with data science technology.**

* Most course assignments

**4. Students will develop skills in programming, iteration, and sequencing.**

* Week 02: | DC | Introduction to R
* Week 04: | DC | Introduction to the Tidyverse
* Week 10: | DC | Data Manipulation with dplyr
* Week 11: | DC | Reshaping Data with tidyr
* Week 12: | DC | Joining Data with dplyr
* Week 13: | DC | Intermediate R
* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

**5. Students will learn how to read data in various formats and write to a file.**

* Week 12: | DC | Introduction to Importing Data in R
* Weeks 15/16: Project #2

**6. Students will learn to manipulate, clean, code, and store data in a tidy format.**

* Week 04: | DC | Introduction to the Tidyverse
* Week 10: | DC | Data Manipulation with dplyr
* Week 11: | DC | Reshaping Data with tidyr
* Week 12: | DC | Joining Data with dplyr
* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

**7. Students will learn to visualize data and models using the grammar of graphics.**

* Week 03: | DC | Understanding Data Visualization
* Week 04: | DC | Introduction to the Tidyverse
* Week 05: | DC | Introduction to Data Visualization with ggplot2
* Week 06: | DC | Visualization Best Practices in R
* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

**8. Students will learn about data scientists, related organizations, and career paths.**

* Week 01: | DC | Understanding Data Science
* Weeks 08/09: Project #1
* Weeks 15/16: Project #2

<hr>

Updated `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`

