---
title: "&#8220;Becoming a Data Scientist&#8221; #1"
subtitle: "STT 2860 Intro to Data Management & Visualization"
author: "PUT YOUR NAME HERE"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---
<hr>
**Instructions:** Go to Dr. Thomley's [Index of "Becoming a Data Scientist" Interviews](https://stat-jet-asu.github.io/STT2860DataScience1/DataScientist/datasciblogindex.html).
Listen to ONE of the seventeen interviews and answer the following questions. *Explain so a reader could get a general idea of what the person said without listening to the interview.* The first sixteen interviews are also collected in a [YouTube playlist](https://www.youtube.com/playlist?list=PLTnOXzOljuWZJo1IlaBcGM74P9vE0Uauc). 
<hr>

**Q01: What is the name of the person interviewed?**

ANSWER:

**Q02: Why did you choose the particular interview you did?**

ANSWER:

**Q03: Does the person consider themselves a data scientist?**

ANSWER:

**Q04: What is their formal and self-taught education in data science?**

ANSWER:

**Q05: What has been their career path? Did they start off in data science?**

ANSWER:

**Q06: What programs/technologies do they use when working in data science?**

ANSWER:

**Q07: What is one interesting (to you) data science problem they have worked on?**

ANSWER:

**Q08: Are there any specific pieces of advice they gave that inspire/resonate with you?**

ANSWER:

**Q09: Was there anything that surprised you or that you particularly identified with?**

ANSWER:

**Q10: Google the person whose interview you watched. What are they doing now?**

ANSWER:

<hr>

