---
title: "Project 3: DataCamp Skills Assessment"
subtitle: "STT 2860 Intro to Data Management & Visualization"
author: "PUT YOUR NAME HERE"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---

<hr>

You will be asked to solve a series of timed challenges (60--120 seconds each) to assess your current level of knowledge about data visualization and manipulation. A full assessment usually contains 15 problems and takes about 10 minutes. Afterward, you will be given recommendations to improve and you can review your answers. This activity is intended to be *formative*, to help you identify strengths and weaknesses. You will be graded on completion, not on your assessment scores.

You will need to look back at both your Project 1 and Project 2 DataCamp Skills Assessments for this assignment.

You can read the DataCamp Assessments FAQ [HERE](https://support.datacamp.com/hc/en-us/articles/360044291373-DataCamp-Assessments-Everything-You-Need-To-Know).

<hr>

#### Take the DataCamp assessment [Data Visualization with R](https://assessment-v2.datacamp.com/data-visualization-r). 

**What score did you achieve on Data Visualization with R last time?**

ANSWER:

**What score did you achieve on Data Visualization with R this time?**

ANSWER:

**You performed better than what percent of other people this time?**

ANSWER:

<hr>

#### Take the DataCamp assessment [Data Manipulation with R](https://assessment-v2.datacamp.com/exploratory-analysis-r). 

**What score did you achieve on Data Manipulation with R last time?**

ANSWER:

**What score did you achieve on Data Manipulation with R this time?**

ANSWER:

**You performed better than what percent of other people this time?**

ANSWER:

<hr>

#### Reflect on Your DataCamp Assessment Results

Recall, STT 2860 Introduction to Data Management & Visualization has no course prerequisites, so we assume no knowledge of R programming for anyone coming into the course (though some students may have some experience). 

Did your scores improve since you completed these two assessments for Project 1 and Project 2?

ANSWER:

Do you feel like the assessments reflect your knowledge here at the end of the semester? Explain. 

ANSWER:

Did you have any particular goals at the start of the semester with respect to this course? Explain.

ANSWER:

What accomplishment are you most proud of? Did you picture yourself achieving this back in January? 

ANSWER:

What course ideas or skills do you still find yourself struggling with the most? Why do you think that is? 

ANSWER:

What is one piece of advice you would give to a future STT 2860 student? Why do you recommend this?

ANSWER:

<hr>

END!



