---
title: "Project 1: DataCamp Skills Assessment"
subtitle: "STT 2860 Intro to Data Management & Visualization"
author: "PUT YOUR NAME HERE"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---

<hr>

You will be asked to solve a series of timed challenges (60--120 seconds each) to assess your current level of knowledge about data visualization and manipulation. A full assessment usually contains 15 problems and takes about 10 minutes. Afterward, you will be given recommendations to improve and you can review your answers. This activity is intended to be *formative*, to help you identify your strengths and weaknesses and measure growth as we move through the semester. **You will be graded on completion, not on your assessment scores.**

You can read the DataCamp Assessments FAQ [HERE](https://support.datacamp.com/hc/en-us/articles/360044291373-DataCamp-Assessments-Everything-You-Need-To-Know).

<hr>

#### Take the DataCamp assessment [Data Visualization with R](https://assessment-v2.datacamp.com/data-visualization-r). 

**What score did you achieve on Data Visualization with R?**

ANSWER:

**You performed better than what percent of other people?**

ANSWER:

**What courses did DataCamp recommend for you to improve?**

ANSWER:

<hr>

#### Take the DataCamp assessment [Data Visualization Theory](https://assessment-v2.datacamp.com/data-visualization-theory). 

**What score did you achieve on Data Visualization Theory?**

ANSWER:

**You performed better than what percent of other people?**

ANSWER:

**What courses did DataCamp recommend for you to improve?**

ANSWER:

<hr>

#### Take the DataCamp assessment [Data Manipulation with R](https://assessment-v2.datacamp.com/exploratory-analysis-r). 

**What score did you achieve on Data Manipulation with R?**

ANSWER:

**You performed better than what percent of other people?**

ANSWER:

**What courses did DataCamp recommend for you to improve?**

ANSWER:

<hr>

#### Reflect on Your DataCamp Assessment Results

Recall, STT 2860 Introduction to Data Management & Visualization has no course prerequisites, so we assume no knowledge of R programming for anyone coming into the course (though some students may have some experience). Given where you started at the beginning of the semester, do you feel these assessments reflect your knowledge here at Week 4? Did anything surprise you? Explain your answer. 

ANSWER:

<hr>

END!

