---
title: "DC Depth Track: Data Science with SQL"
subtitle: "Course Descriptions and Suggested Prerequisites"
date: 'Last Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
---

```{r globaloptions, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```

<hr>

&#10132; Click on the course title to more fully explore the course contents on DataCamp.

### **1st Course: [Introduction to SQL](https://learn.datacamp.com/courses/introduction-to-sql)**

#### **Suggested Prerequisite**

None

#### **DC Course Description**

Much of the world's raw data—from electronic medical records to customer transaction histories—lives in organized collections of tables called relational databases. Being able to wrangle and extract data from these databases using SQL is an essential skill within the data industry and in increasing demand.

In this two-hour introduction to SQL, you'll get to know the theory and the practice through bite-sized videos and interactive exercises where you can put your new-found skills to the test.

SQL is an essential language for building and maintaining relational databases, which opens the door to a range of careers in the data industry and beyond. You’ll start this course by covering data organization, tables, and best practices for database construction.

The second half of this course looks at creating SQL queries for selecting data that you need from your database. You’ll have the chance to practice your querying skills before moving on to customizing and saving your results.

PostgreSQL and SQL Server are two of the most popular SQL flavors. You’ll finish off this course by looking at the differences, benefits, and applications of each. By the end of the course you’ll have some hands-on experience in learning SQL and the grounding to start applying it on projects or continue your learning in a more specialized direction.

### **2nd Course: [Intermediate SQL](https://learn.datacamp.com/courses/intermediate-sql)**

#### **Suggested Prerequisite**

Introduction to SQL

#### **DC Course Description**

SQL is the most popular language for turning raw data stored in a database into actionable insights. Using a database of films made around the world, this course covers:

✓ How to filter and compare data  
✓ How to use aggregate functions to summarize data  
✓ How to sort and group your data  
✓ How to present your data cleanly using tools such as rounding and aliasing  

Accompanied at every step with hands-on practice queries, this course teaches you everything you need to know to analyze data using your own SQL code today!

### **3rd Course: [Joining Data in SQL](https://app.datacamp.com/learn/courses/joining-data-in-sql)**

#### **Suggested Prerequisite**

Intermediate SQL

#### **DC Course Description**

Joining data is an essential skill which enables us to draw information from separate tables together into a single, meaningful set of results. Learn to supercharge your queries using table joins and relational set theory in this course on joining data. In this course, you’ll learn how to:

✓ Work with more than one table in SQL  
✓ Use inner joins, outer joins and cross joins  
✓ Leverage set theory, including unions, intersect, and except clauses  
✓ Create nested queries  

Every step is accompanied by exercises and opportunities to apply the theory and grow your confidence in SQL.

<hr>

&#10132; If you find any errors on this page, please contact Dr. Thomley via your Private Forum on AsULearn.

<hr>
