---
title: "DC Depth Track: Interactive Data Visualization in R"
subtitle: "Course Descriptions and Suggested Prerequisites"
date: 'Last Update: `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
---

```{r globaloptions, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```

<hr>

&#10132; Click on the course title to more fully explore the course contents on DataCamp.

### **1st Course: [Interactive Maps with leaflet in R](https://learn.datacamp.com/courses/interactive-maps-with-leaflet-in-r)**

#### **Suggested Prerequisite**

Introduction to the Tidyverse

#### **DC Course Description**

Get ready to have some fun with maps! Interactive Maps with leaflet in R will give you the tools to make attractive and interactive web maps using spatial data and the tidyverse. In this course, you will create maps using the IPEDS dataset, which contains data on U.S. colleges and universities. Along the way, you will customize our maps using labels, popups, and custom markers, and add layers to enhance interactivity. Following the course, you will be able to create and customize your own interactive web maps to reveal patterns in your data.

### **2nd Course: [Interactive Data Visualization with plotly in R](https://app.datacamp.com/learn/courses/interactive-data-visualization-with-plotly-in-r)**

#### **Suggested Prerequisite**

Introduction to the Tidyverse

#### **DC Course Description**

Interactive graphics allow you to manipulate plotted data to gain further insight. As an example, an interactive graphic would allow you to zoom in on a subset of your data without the need to create a new plot. In this course, you will learn how to create and customize interactive graphics in plotly using the R programming language. Along the way, you will review data visualization best practices and be introduced to new plot types such as scatterplot matrices and binned scatterplots.

### **3rd Course (Option 1): [Intermediate Interactive Data Visualization with plotly in R](https://app.datacamp.com/learn/courses/intermediate-interactive-data-visualization-with-plotly-in-r)**

#### **Suggested Prerequisite**

Interactive Data Visualization with plotly in R

#### **DC Course Description**

The plotly package enables the construction of interactive and animated graphics entirely within R. This goes beyond basic interactivity such as panning, zooming, and tooltips. In this course, you will extend your understanding of plotly to create animated and linked interactive graphics, which will enable you to communicate multivariate stories quickly and effectively. Along the way, you will review the basics of plotly, learn how to wrangle your data in new ways to facilitate cumulative animations, and learn how to add filters to your graphics without using Shiny.

**Choose only one of the 3rd Course options.**

### **3rd Course (Option 2): [Visualizing Big Data with Trelliscope in R](https://app.datacamp.com/learn/courses/visualizing-big-data-with-trelliscope-in-r)**

#### **Suggested Prerequisite**

Introduction to the Tidyverse

#### **DC Course Description**

Having honed your visualization skills by learning ggplot2, it's now time to tackle larger datasets. In this course, you will learn several techniques for visualizing big data, with particular focus on the scalable visualization technique of faceting. You will learn how to put this technique into action using the Trelliscope approach as implemented in the trelliscopejs R package. Trelliscope plugs seamlessly into standard R workflows and produces interactive visualizations that allow you to visually explore your data in detail. By the end of this course, you will be able to easily create interactive exploratory displays of large datasets that will help you and your colleagues gain new insights into your data.

**Choose only one of the 3rd Course options.**

<hr>

&#10132; If you find any errors on this page, please contact Dr. Thomley via your Private Forum on AsULearn.

<hr>
