---
title: "DC Depth Track: Visualizing Spatial Data"
subtitle: "Course Descriptions and Suggested Prerequisites"
date: 'Last Update: `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
---

```{r globaloptions, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```

<hr>

&#10132; Click on the course title to more fully explore the course contents on DataCamp.

### **1st Course: [Interactive Maps with leaflet in R](https://learn.datacamp.com/courses/interactive-maps-with-leaflet-in-r)**

#### **Suggested Prerequisite**

Introduction to the Tidyverse

#### **DC Course Description**

Get ready to have some fun with maps! Interactive Maps with leaflet in R will give you the tools to make attractive and interactive web maps using spatial data and the tidyverse. In this course, you will create maps using the IPEDS dataset, which contains data on U.S. colleges and universities. Along the way, you will customize our maps using labels, popups, and custom markers, and add layers to enhance interactivity. Following the course, you will be able to create and customize your own interactive web maps to reveal patterns in your data.

### **2nd Course: [Visualizing Geospatial Data in R](https://learn.datacamp.com/courses/visualizing-geospatial-data-in-r)**

#### **Suggested Prerequisite**

Introduction to Data Visualization with ggplot2

#### **DC Course Description**

Where should you buy a house to get the most value for your money? Your first step might be to make a map, but spatial analysis in R can be intimidating because of the complicated objects the data often live in.

This course will introduce you to spatial data by starting with objects you already know about, data frames, before introducing you to the special objects from the sp and raster packages used to represent spatial data for analysis in R. You'll learn to read, explore, and manipulate these objects with the big payoff of being able to use the tmap package to make maps.

By the end of the course you will have made maps of property sales in a small town, populations of the countries of the world, the distribution of people in the North East of the USA, and median income in the neighborhoods of New York City.

### **3rd Course: [Spatial Analysis with sf and raster in R](https://app.datacamp.com/learn/courses/spatial-analysis-with-sf-and-raster-in-r)**

#### **Suggested Prerequisite**

Visualizing Geospatial Data in R

#### **DC Course Description**

There has never been a better time to use R for spatial analysis! The sf package has made working with vector data in R a breeze and the raster package provides a set of powerful and intuitive tools to work gridded data like satellite imagery. Instead of the painful process of performing your spatial analysis in GIS systems like ArcGIS or QGIS and then shuffling your results into another system for analysis, you can move your entire spatial analysis workflow into R. In this course you will learn why the sf package is rapidly taking over spatial analysis in R. You will read in spatial data, manipulate vectors using the dplyr package and learn how to work with coordinate reference systems. You'll also learn how to perform geoprocessing of vectors including buffering, spatial joins, computing intersections, simplifying and measuring distance. With rasters, you will aggregate, reclassify, crop, mask, and extract. The last chapter of the course is devoted to showing you how to make maps in R with the ggplot2 and tmap packages and performing a fun mini-analysis that brings together all your new skills.

<hr>

&#10132; If you find any errors on this page, please contact Dr. Thomley via your Private Forum on AsULearn.

<hr>
