---
title: "Course Descriptions for Spatial Visualization Depth Option"
date: 'Last Update: `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
---

```{r globaloptions, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```

<hr>

&#10132; Click on the course title to more fully explore the course contents on DataCamp.

### **1st Course: [Interactive Maps with leaflet in R](https://learn.datacamp.com/courses/interactive-maps-with-leaflet-in-r)**

#### **Suggested Prerequisite**

Introduction to the Tidyverse

#### **DC Course Description**

Get ready to have some fun with maps! Interactive Maps with leaflet in R will give you the tools to make attractive and interactive web maps using spatial data and the tidyverse. In this course, you will create maps using the IPEDS dataset, which contains data on U.S. colleges and universities. Along the way, you will customize our maps using labels, popups, and custom markers, and add layers to enhance interactivity. Following the course, you will be able to create and customize your own interactive web maps to reveal patterns in your data.

### **2nd Course: [Intermediate Data Visualization with ggplot2](https://learn.datacamp.com/courses/intermediate-data-visualization-with-ggplot2)**

#### **Suggested Prerequisite**

Introduction to Data Visualization with ggplot2

#### **DC Course Description**

This ggplot2 course builds on your knowledge from the introductory course to produce meaningful explanatory plots. Statistics will be calculated on the fly and you’ll see how Coordinates and Facets aid in communication. You’ll also explore details of data visualization best practices with ggplot2 to help make sure you have a sound understanding of what works and why. By the end of the course, you’ll have all the tools needed to make a custom plotting function to explore a large data set, combining statistics and excellent visuals.

### **3rd Course: [Visualizing Geospatial Data in R](https://learn.datacamp.com/courses/visualizing-geospatial-data-in-r)**

#### **Suggested Prerequisite**

Introduction to Data Visualization with ggplot2

#### **DC Course Description**

Where should you buy a house to get the most value for your money? Your first step might be to make a map, but spatial analysis in R can be intimidating because of the complicated objects the data often live in.

This course will introduce you to spatial data by starting with objects you already know about, data frames, before introducing you to the special objects from the sp and raster packages used to represent spatial data for analysis in R. You'll learn to read, explore, and manipulate these objects with the big payoff of being able to use the tmap package to make maps.

By the end of the course you will have made maps of property sales in a small town, populations of the countries of the world, the distribution of people in the North East of the USA, and median income in the neighborhoods of New York City.

<hr>

&#10132; If you find any errors on this page, please contact Dr. Thomley via your Private Forum on AsULearn.

<hr>
