---
title: "Becoming a Data Scientist"
subtitle: "STT2860 Project 01 Spring 2023"
author: "PUT YOUR NAME HERE"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---
<hr>

**Q01: What is the name of the person interviewed?**

ANSWER:

**Q02: Why did you choose the particular interview you did?**

ANSWER:

**Q03: Does the person consider themselves a data scientist?**

ANSWER:

**Q04: What is their formal and self-taught education in data science?**

ANSWER:

**Q05: What has been their career path? Did they start off in data science?**

ANSWER:

**Q06: What programs/technologies do they use when working in data science?**

ANSWER:

**Q07: What is one interesting (to you) data science problem they have worked on?**

ANSWER:

**Q08: Are there any specific pieces of advice they gave that inspire/resonate with you?**

ANSWER:

**Q09: Was there anything that surprised you or that you particularly identified with?**

ANSWER:

**Q09: Was there anything that surprised you or that you particularly identified with?**

ANSWER:

**Q10: Google the person whose interview you watched. What are they doing now?**

ANSWER:

<hr>

